# Generated by Django 3.0.8 on 2020-10-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='gender',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='ttype',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
